language: php

php:
  - '7.1'

before_install:
- composer require php-coveralls/php-coveralls
- composer install --dev
 
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml tests/UserProfile.php
 
after_script:
- php vendor/bin/php-coveralls -v