<?php
/**
 * Created by PhpStorm.
 * User: kulakov
 * Date: 14.05.18
 * Time: 12:07
 */


class UITest extends PHPUnit_Extensions_Selenium2TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->setBrowserUrl('http://localhost/phpunit');
        $this->setHost('localhost');
        $this->setPort(4444);
        $this->setBrowser('chrome');
    }

    public function testFormSubmission() {
        $this->url('http://localhost/phpunit/login.php');
        $this->byName('password')->value("pass1");
        $this->byName('login')->value("name1");
        $this->byId('loginForm')->submit();
        $content = $this->byTag('body')->text();
        $this->assertStringMatchesFormat("name: name1\nemail: name1@localhost", $content);
    }

    protected function _waitAndFind($selector) {
        $element = $this->waitUntil(function($testCase) use ($selector) {
            try {
                $this->log($testCase);
                $element = $testCase->byId($selector);
                if ($element->displayed()) {
                    return $element;
                }
            } catch (PHPUnit_Extensions_Selenium2TestCase_WebDriverException $e) {}
        }, 8000);
        return $element;
    }

    /**
     * Override this method from \PHPUnit_Framework_TestCase so we can capture a screenshot.
     *
     * @return void
     * @throws Throwable
     */
    public function onNotSuccessfulTest(Throwable $e)
    {
        try {
            $filedata = $this->currentScreenshot();
            $file = './testfails/' . basename(get_class($this)) . '.png';
            file_put_contents($file, $filedata);
        } catch (Exception $ex) {}
        parent::onNotSuccessfulTest($e);
    }
}
